### ISSUE TITLE
Bring over the autogen bindings from CTRE

### ISSUE THREAD

**Issue by virtuald** [robotpy/robotpy-rev#1]
It's going to be really similar for simulation autogen + class autogen.

**Comment by virtuald** [comment]
One change - they have really nice doxygen comments , so it would be nice to extract/transform that automatically if possible.

**Comment by auscompgeek** [comment]
CppHeaderParser finds Doxygen comments for us, so putting them through [sphinxify](https://github.com/auscompgeek/sphinxify) should be straightforward.
