### ISSUE TITLE
Test this on real hardware

### ISSUE THREAD

**Issue by virtuald** [robotpy/robotpy-rev#2]
Does it work? Who knows.

**Comment by robobenklein** [comment]
IT WORKKKKSSSS

**Comment by robobenklein** [comment]
Works with this code on real robot: https://gitlab.com/utk-robotics/ri3d/tree/rev-can

**Comment by auscompgeek** [comment]
Heh, nice.

I built this from #5 just yesterday, give this a go: https://vovo.id.au/tmp/robotpy_rev-0.0.1a0.post0.dev28-cp37-cp37m-linux_armv7l.whl
