### ISSUE TITLE
Update to robotpy-rev 2020 not installing

### ISSUE THREAD

**Issue by Trent1048** [robotpy/robotpy-rev#25]
The previous 2019 version of rev installs correctly and works but when I try to run `pip install --upgrade robotpy-rev` to upgrade to the 2020 release, it gives me a bunch of errors and refuses to install. First it says it is missing build requirements in `pyproject.toml` for `robotpy-rev` then trys to build wheels but fails, giving the final error message of: `ERROR: Could not build wheels for robotpy-rev which use PEP 517 and cannot be installed directly` I have attached a text document with all the error messages and would appreciate some help figuring out how to update the rev library on my computer.

[errors.txt](https://github.com/robotpy/robotpy-rev/files/4132501/errors.txt)

**Comment by virtuald** [comment]
As mentioned in the project README, REV does not support 32-bit Windows programs, so neither can we. We need to make a better error message for when this happens.

You should uninstall your 32-bit python, install a 64-bit python, and then you should be able to install it.

**Comment by Trent1048** [comment]
Thank you.
